classDiagram
class ChatRoomService {
currentUserId: null
-chatRoomRepository: ChatRoomRepository
-merchantRepository: MerchantRepository
-chatRepository: ChatRepository
-cache: Cache
-baseCacheKey: String
createChatRoom(): int
getChatRoomId(): int
getAllChatRooms(): ChatRoomVM?[0..*]
}
ChatRoomService ..> ChatRoomRepository
ChatRoomService ..> MerchantRepository
ChatRoomService ..> ChatRepository
ChatRoomService ..> Cache
class CartService {
-cartRepository: CartRepository
-productRepository: ProductRepository
-merchantRepository: MerchantRepository
-productMediaRepository: ProductMediaRepository
-cache: Cache
currentUserId: null
-baseCacheKey: String
getCarts(): CartVM[0..*]
deleteCart(): void
createCart(): int?
updateCart(): int?
}
CartService ..> CartRepository
CartService ..> ProductRepository
CartService ..> MerchantRepository
CartService ..> ProductMediaRepository
CartService ..> Cache
class PostLikeService {
currentUserId: null
-postLikeRepository: PostLikeRepository
-cache: Cache
merchantSideCacheKeyPattern: String
likePost(): void
unlikePost(): void
}
PostLikeService ..> PostLikeRepository
PostLikeService ..> Cache
class OrderService {
currentUserId: null
-orderRepository: OrderRepository
-orderProductRepository: OrderProductRepository
-cartRepository: CartRepository
-merchantRepository: MerchantRepository
-productRepository: ProductRepository
-productMediaRepository: ProductMediaRepository
-userRepository: UserRepository
-cache: Cache
-baseCacheKey: String
merchantSideCacheKeyPattern: String
getAllOrders(): OrderVM[0..*]
createOrders(): void
}
OrderService ..> OrderRepository
OrderService ..> OrderProductRepository
OrderService ..> CartRepository
OrderService ..> MerchantRepository
OrderService ..> ProductRepository
OrderService ..> ProductMediaRepository
OrderService ..> UserRepository
OrderService ..> Cache
class ChatService {
-chatRepository: ChatRepository
-cache: Cache
currentUserId: null
-baseCacheKey: String
merchantSideCacheKeyPattern: String
createChat(): ChatVM?
getChatsByChatRoomId(): ChatVM[0..*]
}
ChatService ..> ChatRepository
ChatService ..> Cache
class MerchantService {
currentUserId: null
-merchantRepository: MerchantRepository
-postRepository: PostRepository
-promoMediaRepository: PromoMediaRepository
-liveStreamRepository: LiveStreamRepository
-productRepository: ProductRepository
-productMediaRepository: ProductMediaRepository
-cartRepository: CartRepository
-cache: Cache
-baseCacheKey: String
getMerchantById(): MerchantVM
getMerchantPosts(): MerchantPostsVM[0..*]
getMerchantLiveStreams(): MerchantLivestreamsVM[0..*]
getMerchantProducts(): MerchantProductsVM[0..*]
}
MerchantService ..> MerchantRepository
MerchantService ..> PostRepository
MerchantService ..> PromoMediaRepository
MerchantService ..> LiveStreamRepository
MerchantService ..> ProductRepository
MerchantService ..> ProductMediaRepository
MerchantService ..> CartRepository
MerchantService ..> Cache
class LiveStreamService {
currentUserId: null
-liveStreamRepository: LiveStreamRepository
-cache: Cache
-baseCacheKey: String
getLiveStreamById(): LiveStreamVM
getAllLiveStreams(): LiveStreamVM[0..*]
}
LiveStreamService ..> LiveStreamRepository
LiveStreamService ..> Cache
class LiveStreamProductsService {
currentUserId: null
-liveStreamProductRepository: LiveStreamProductRepository
-productRepository: ProductRepository
-productMediaRepository: ProductMediaRepository
-cache: Cache
-baseCacheKey: String
getLiveStreamProductsByLiveStreamId(): LiveStreamProductsVM[0..*]
}
LiveStreamProductsService ..> LiveStreamProductRepository
LiveStreamProductsService ..> ProductRepository
LiveStreamProductsService ..> ProductMediaRepository
LiveStreamProductsService ..> Cache
class PostService {
currentUserId: null
-postRepository: PostRepository
-merchantRepository: MerchantRepository
-postProductsRepository: PostProductsRepository
-promoMediaRepository: PromoMediaRepository
-postLikeRepository: PostLikeRepository
-postSaveRepository: PostSaveRepository
-productRepository: ProductRepository
-productMediaRepository: ProductMediaRepository
-productCategoryRepository: ProductCategoryRepository
-productCategoryMapsRepository: ProductCategoryMapsRepository
-cartRepository: CartRepository
-cache: Cache
-baseCacheKey: String
merchantSideCacheKeyPattern: String
getAllPosts(): PostVM[0..*]
createPost(): PostVM?
getPostById(): PostVM?
getSimilarPosts(): PostVM[0..*]
-_buildPostVMs(): PostVM[0..*]
-_getPostsByCategory(): PostModel[0..*]
}
PostService ..> PostRepository
PostService ..> MerchantRepository
PostService ..> PostProductsRepository
PostService ..> PromoMediaRepository
PostService ..> PostLikeRepository
PostService ..> PostSaveRepository
PostService ..> ProductRepository
PostService ..> ProductMediaRepository
PostService ..> ProductCategoryRepository
PostService ..> ProductCategoryMapsRepository
PostService ..> CartRepository
PostService ..> Cache
class UserService {
currentUserId: int
-userRepository: UserRepository
-postRepository: PostRepository
-postLikeRepository: PostLikeRepository
-postSaveRepository: PostSaveRepository
-promoMediaRepository: PromoMediaRepository
-cache: Cache
-baseCacheKey: String
getUserById(): UserModel?
getUserProfile(): UserProfileVM
getLikedPosts(): UserProfileLikedSavedPostsVM[0..*]
getSavedPosts(): UserProfileLikedSavedPostsVM[0..*]
}
UserService ..> UserRepository
UserService ..> PostRepository
UserService ..> PostLikeRepository
UserService ..> PostSaveRepository
UserService ..> PromoMediaRepository
UserService ..> Cache
class PostSaveService {
currentUserId: null
-cache: Cache
merchantSideCacheKeyPattern: String
-postSaveRepository: PostSaveRepository
savePost(): void
unsavePost(): void
}
PostSaveService ..> Cache
PostSaveService ..> PostSaveRepository
class LiveStreamChatService {
currentUserId: null
-liveStreamChatRepository: LiveStreamChatRepository
-userRepository: UserRepository
-cache: Cache
-baseCacheKey: String
merchantSideCacheKeyPattern: String
getAllLiveStreamChatByLiveStreamId(): LiveStreamChatVM[0..*]
createLiveStreamChat(): LiveStreamChatVM?
}
LiveStreamChatService ..> LiveStreamChatRepository
LiveStreamChatService ..> UserRepository
LiveStreamChatService ..> Cache
class AuthService {
login(): Role?
signUpUser(): void
logout(): void
}
class ChatRoomService {
currentMerchantId: null
-chatRoomRepository: ChatRoomRepository
-userRepository: UserRepository
-chatRepository: ChatRepository
-cache: Cache
-baseCacheKey: String
getAllChatRooms(): MerchantChatRoomVM?[0..*]
}
ChatRoomService ..> ChatRoomRepository
ChatRoomService ..> UserRepository
ChatRoomService ..> ChatRepository
ChatRoomService ..> Cache
class ProductService {
currentMerchantId: null
-productRepository: ProductRepository
-productMediaRepository: ProductMediaRepository
-cache: Cache
-baseCacheKey: String
userSideCacheKeyPattern: String
getAllProducts(): ProductVM[0..*]
getAllProductsForCurrentMerchant(): ProductVM[0..*]
createProduct(): ProductVM?
getProductById(): ProductVM?
updateProduct(): ProductVM?
deleteProduct(): void
}
ProductService ..> ProductRepository
ProductService ..> ProductMediaRepository
ProductService ..> Cache
class OrderService {
currentMerchantId: null
-orderRepository: OrderRepository
-orderProductRepository: OrderProductRepository
-productRepository: ProductRepository
-productMediaRepository: ProductMediaRepository
-cache: Cache
-baseCacheKey: String
userSideCacheKeyPattern: String
getAllOrders(): OrderMerchantVM[0..*]
updateOrder(): void
deleteOrder(): void
}
OrderService ..> OrderRepository
OrderService ..> OrderProductRepository
OrderService ..> ProductRepository
OrderService ..> ProductMediaRepository
OrderService ..> Cache
class ChatService {
-chatRepository: ChatRepository
-cache: Cache
currentMerchantId: null
-baseCacheKey: String
userSideCacheKeyPattern: String
createChat(): int
getChatsByChatRoomId(): MerchantChatVM[0..*]
}
ChatService ..> ChatRepository
ChatService ..> Cache
class LiveStreamService {
currentMerchantId: null
-liveStreamRepository: LiveStreamRepository
-liveStreamChatRepository: LiveStreamChatRepository
-liveStreamProductRepository: LiveStreamProductRepository
-productRepository: ProductRepository
-productMediaRepository: ProductMediaRepository
-cache: Cache
-baseCacheKey: String
userSideCacheKeyPattern: String
getAllLiveStreams(): MerchantLiveStreamsVM[0..*]
getLiveStreamById(): MerchantLiveStreamsVM?
createLiveStream(): MerchantLiveStreamsVM?
updateLiveStream(): MerchantLiveStreamsVM?
deleteLiveStream(): void
}
LiveStreamService ..> LiveStreamRepository
LiveStreamService ..> LiveStreamChatRepository
LiveStreamService ..> LiveStreamProductRepository
LiveStreamService ..> ProductRepository
LiveStreamService ..> ProductMediaRepository
LiveStreamService ..> Cache
class PostService {
currentMerchantId: null
-postRepository: PostRepository
-merchantRepository: MerchantRepository
-postProductsRepository: PostProductsRepository
-promoMediaRepository: PromoMediaRepository
-postLikeRepository: PostLikeRepository
-postSaveRepository: PostSaveRepository
-productRepository: ProductRepository
-productMediaRepository: ProductMediaRepository
-productCategoryRepository: ProductCategoryRepository
-productCategoryMapsRepository: ProductCategoryMapsRepository
-cartRepository: CartRepository
-cache: Cache
-baseCacheKey: String
userSideCacheKeyPattern: String
getAllPosts(): PostVM[0..*]
getAllPostsForCurrentMerchant(): PostVM[0..*]
createPost(): PostVM?
getPostById(): PostVM?
updatePost(): PostVM?
deletePost(): void
-_buildPostVMs(): PostVM[0..*]
-_getPostsByCategory(): PostModel[0..*]
-_getPostsByCategoryForCurrentMerchant(): PostModel[0..*]
}
PostService ..> PostRepository
PostService ..> MerchantRepository
PostService ..> PostProductsRepository
PostService ..> PromoMediaRepository
PostService ..> PostLikeRepository
PostService ..> PostSaveRepository
PostService ..> ProductRepository
PostService ..> ProductMediaRepository
PostService ..> ProductCategoryRepository
PostService ..> ProductCategoryMapsRepository
PostService ..> CartRepository
PostService ..> Cache
