%% DAK LOUK CORE
classDiagram
class AppSession
AppSession : +instance$ AppSession
AppSession o-- AppSession
AppSession : -_userRepository UserRepository
AppSession o-- UserRepository
AppSession : -_merchantRepository MerchantRepository
AppSession o-- MerchantRepository
AppSession : -_keyUserId$ String
AppSession : -_keyUsername$ String
AppSession : -_keyRole$ String
AppSession : -_keyPhone$ String
AppSession : -_keyAddress$ String
AppSession : -_keyMerchantId$ String
AppSession : -_keyMerchantUsername$ String
AppSession : -_keyMerchantProfileImageUrl$ String
AppSession : -_userId int?
AppSession : -_username String?
AppSession : -_phone String?
AppSession : -_address String?
AppSession : -_merchantId int?
AppSession : -_merchantUsername String?
AppSession : -_merchantProfileImageUrl String?
AppSession : -_role Role?
AppSession o-- Role
AppSession : +isLoggedIn bool
AppSession : +userId int?
AppSession : +username String?
AppSession : +phone String?
AppSession : +address String?
AppSession : +role Role?
AppSession o-- Role
AppSession : +merchantId int?
AppSession : +merchantUsername String?
AppSession : +merchantProfileImageUrl String?
AppSession : +init() dynamic
AppSession : +login() dynamic
AppSession : +signUpUser() dynamic
AppSession : +logout() dynamic

class OrderStatusEnum
<<enumeration>> OrderStatusEnum
OrderStatusEnum : +index int
OrderStatusEnum : +values$ List~OrderStatusEnum~
OrderStatusEnum : +waiting$ OrderStatusEnum
OrderStatusEnum o-- OrderStatusEnum
Enum <|.. OrderStatusEnum

class Role
<<enumeration>> Role
Role : +index int
Role : +values$ List~Role~
Role : +user$ Role
Role o-- Role
Enum <|.. Role

class UserTabs
<<enumeration>> UserTabs
UserTabs : +index int
UserTabs : +values$ List~UserTabs~
UserTabs : +home$ UserTabs
UserTabs o-- UserTabs
Enum <|.. UserTabs

class MerchantTabs
<<enumeration>> MerchantTabs
MerchantTabs : +index int
MerchantTabs : +values$ List~MerchantTabs~
MerchantTabs : +orders$ MerchantTabs
MerchantTabs o-- MerchantTabs
Enum <|.. MerchantTabs

class MediaType
<<enumeration>> MediaType
MediaType : +index int
MediaType : +values$ List~MediaType~
MediaType : +image$ MediaType
MediaType o-- MediaType
MediaType : +video$ MediaType
MediaType o-- MediaType
Enum <|.. MediaType

class Clauses
Clauses : +where$ _Where
Clauses o-- _Where
Clauses : +orderBy$ _OrderBy
Clauses o-- _OrderBy
Clauses : +like$ _Like
Clauses o-- _Like

class _Where
_Where : +clause String
_Where : +args List~Object?~
_Where : +eq() _Where
_Where : +and() _Where
_Where : +or() _Where
_Where : +gt() _Where
_Where : +gte() _Where
_Where : +lt() _Where
_Where : +lte() _Where
_Where : +not() _Where
_Where : +isNull() _Where
_Where : +isNotNull() _Where
_Where : +inVal() _Where
_Where : +notInVal() _Where
_Where : +between() _Where
_Where : +notBetween() _Where
_Where : +neq() _Where

class _OrderBy
_OrderBy : +clause String
_OrderBy : +asc() _OrderBy
_OrderBy : +desc() _OrderBy
_OrderBy : +caseWhen() _OrderBy
_OrderBy : +thenBy() _OrderBy

class _Like
_Like : +clause String
_Like : +args List~Object?~
_Like : +like() _Like
_Like : +notLike() _Like

class Hasher
Hasher : +md5Hash()$ String
Hasher : +sha256Hash()$ String
Hasher : +sha512Hash()$ String

class Validator
Validator : +validateUsername()$ String?
Validator : +validateEmail()$ String?
Validator : +validatePassword()$ String?

class AppError
AppError : +type ErrorType
AppError o-- ErrorType
AppError : +message String?
Exception <|.. AppError

class ErrorType
<<enumeration>> ErrorType
ErrorType : +index int
ErrorType : +values$ List~ErrorType~
ErrorType : +NOT_FOUND$ ErrorType
ErrorType o-- ErrorType
ErrorType : +ALREADY_EXISTS$ ErrorType
ErrorType o-- ErrorType
ErrorType : +DB_ERROR$ ErrorType
ErrorType o-- ErrorType
ErrorType : +CACHE_ERROR$ ErrorType
ErrorType o-- ErrorType
ErrorType : +CORRUPTED_DATA$ ErrorType
ErrorType o-- ErrorType
ErrorType : +INVALID_INPUT$ ErrorType
ErrorType o-- ErrorType
ErrorType : +MISSING_INPUT$ ErrorType
ErrorType o-- ErrorType
ErrorType : +INVALID_STATE$ ErrorType
ErrorType o-- ErrorType
ErrorType : +UNAUTHORIZED$ ErrorType
ErrorType o-- ErrorType
ErrorType : +SESSION_EXPIRED$ ErrorType
ErrorType o-- ErrorType
ErrorType : +FORBIDDEN$ ErrorType
ErrorType o-- ErrorType
ErrorType : +OPERATION_NOT_ALLOWED$ ErrorType
ErrorType o-- ErrorType
ErrorType : +LIMIT_REACHED$ ErrorType
ErrorType o-- ErrorType
ErrorType : +INTERNAL_ERROR$ ErrorType
ErrorType o-- ErrorType
ErrorType : +UNKNOWN$ ErrorType
ErrorType o-- ErrorType
Enum <|.. ErrorType

class MediaModel
MediaModel : +url String
MediaModel : +type MediaType
MediaModel o-- MediaType

class MediaPickerSheet
MediaPickerSheet : +show()$ dynamic

class MediaPicker
MediaPicker : -_picker$ ImagePicker
MediaPicker o-- ImagePicker
MediaPicker : +pickAndStoreMedia()$ dynamic

